#version: '3.8'
services:
  # urlaubsplanung
  urlaubsplanung:
    build:
      context: .
      dockerfile: Dockerfile
    image: hiiico/vacation_planning-urlaubsplanung  # Add this line for pushing
    container_name: main-app
    ports:
      - "8080:8080"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${MYSQL_HOST}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BROKER}
    networks:
      - app-network
#    restart: unless-stopped
    expose:
      - "8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 50s
      retries: 10
networks:
  app-network:
    external: true
    name: app-network
